trigger:
  branches:
    include: ['add-home-management']
  tags:
    include: ['*']

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'vscode-dockerregistry'
    repository: 'vscode'
    command: 'buildAndPush'
    Dockerfile: 'containers/azure-machine-learning-python-3/.devcontainer/Dockerfile'



